resources:
- oauth.yaml
- project-leaders.yaml
- self-provisioners.yaml
- ../app/k8s/namespace.yaml
- ../app/k8s
secretGenerator:
- name: htpasswd-secret
  namespace: openshift-config
  files:
  - htpasswd=htpasswd-secret-data
generatorOptions:
  disableNameSuffixHash: true
